{% set name = "vaex-core" %}
{% set version = "0.5.0" %}
{% set sha256 = "7d21060707046996a1e0880a78e0c811d45fdff614913f876990a2869ad65903" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
     - vaex = vaex.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - astropy >=1
    - aplus
    - futures >=2.2.0  # [py27]
    - future >=0.15.2
    - pyyaml
    - progressbar2
    - psutil >=1.2.1
    - requests
    - six
    - cloudpickle

test:
  imports:
    - vaex
    - vaex.vaexfast
    - vaex.core

about:
  home: https://www.github.com/maartenbreddels/vaex
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Core of vaex'
  doc_url: http://vaex.astro.rug.nl/latest
  dev_url: https://www.github.com/maartenbreddels/vaex

extra:
  recipe-maintainers:
    - maartenbreddels
